name: GamePlan Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "GamePlan-Frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "GamePlan-Frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: GamePlan-Frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: GamePlan-Frontend/package-lock.json

      - run: npm ci
      - run: npm run build
